name: GitHub Actions Demo
on: [push]
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
        node-version: '12.x'
      - run: npm install .
      - run: npm build
