name: GitHub Actions Demo
on: [push]
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g @angular/cli
      - run: npm install .
      - run: ng build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          BRANCH: gh-pages
          FOLDER: dist/wiki-pulse-angular
